//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon App {
            get {
                object obj = ResourceManager.GetObject("App", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDR,Heavy,9
        ///DDR,Oni,9
        ///Celebrate Night,Heavy,7
        ///Maxx Unlimited,Heavy,10
        ///Maxx Unlimited,Standard,8.
        /// </summary>
        internal static string custom {
            get {
                return ResourceManager.GetString("custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .59,Heavy,7
        ///1998,Heavy,7
        ///20 november,Heavy,7
        ///321 Stars,Heavy,8
        ///5.1.1.,Heavy,7
        ///A,Heavy,8
        ///A,Challenge,9
        ///ABSOLUTE,Heavy,8
        ///Abyss,Heavy,7
        ///Across the nightmare,Heavy,8
        ///Across the nightmare,Challenge,9
        ///AFRONOVA,Heavy,9
        ///AFRONOVA (FROM NONSTOP MEGAMIX),Challenge,8
        ///AFRONOVA PRIMEVAL,Heavy,9
        ///AFTER THE GAME OF LOVE,Heavy,5
        ///air,Heavy,7
        ///AM-3P,Heavy,8
        ///AM-3P (303 BASS MIX),Heavy,7
        ///AM-3P (AM EAST mix),Challenge,7
        ///AOI SHOUDOU (for EXTREME),Heavy,8
        ///B4U,Heavy,8
        ///B4U (B4 ZA BEAT MIX),Challenge,7
        ///BABY BABY G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ddr_heavy {
            get {
                return ResourceManager.GetString("ddr_heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .59,Heavy,7
        ///1998,Heavy,7
        ///20 november,Heavy,7
        ///321 Stars,Heavy,8
        ///5.1.1.,Heavy,7
        ///A,Heavy,8
        ///A,Challenge,9
        ///ABSOLUTE,Heavy,8
        ///Abyss,Heavy,7
        ///Across the nightmare,Heavy,8
        ///Across the nightmare,Challenge,9
        ///AFRONOVA,Heavy,9
        ///AFRONOVA (FROM NONSTOP MEGAMIX),Challenge,8
        ///AFRONOVA PRIMEVAL,Heavy,9
        ///AFTER THE GAME OF LOVE,Heavy,5
        ///air,Heavy,7
        ///AM-3P,Heavy,8
        ///AM-3P (303 BASS MIX),Heavy,7
        ///AM-3P (AM EAST mix),Challenge,7
        ///AOI SHOUDOU (for EXTREME),Heavy,8
        ///B4U,Heavy,8
        ///B4U (B4 ZA BEAT MIX),Challenge,7
        ///BABY BABY G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ddr_heavystandard {
            get {
                return ResourceManager.GetString("ddr_heavystandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .59,Standard,6
        ///1998,Standard,5
        ///20, november,Standard,4
        ///321 Stars,Standard,6
        ///5.1.1.,Standard,5
        ///A,Standard,6
        ///ABSOLUTE,Standard,5
        ///Abyss,Standard,5
        ///Across the nightmare,Standard,6
        ///AFRONOVA,Standard,7
        ///AFRONOVA PRIMEVAL,Standard,6
        ///AFTER THE GAME OF LOVE,Standard,4
        ///air,Standard,5
        ///AM-3P,Standard,6
        ///AM-3P (303 BASS MIX),Standard,6
        ///AOI SHOUDOU (for EXTREME),Standard,5
        ///B4U,Standard,5
        ///BABY BABY GIMME YOUR LOVE,Standard,3
        ///bag,Standard,7
        ///Be in my paradise,Standard,3
        ///BE LOVIN,Standard,6
        ///BREAK DOWN!,Sta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ddr_standard {
            get {
                return ResourceManager.GetString("ddr_standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !,Expert,12
        ///Agent Blatant,Expert,10
        ///Amore,Expert,9
        ///Anubis,Expert,10
        ///Baby Don&apos;t You Want Me,Expert,9
        ///Bend Your Mind,Expert,10
        ///Birdie,Expert,9
        ///Bloodrush,Expert,12
        ///Boogie Down,Expert,9
        ///Bouff,Expert,10
        ///Bumble Bee,Expert,9
        ///Charlene,Expert,11
        ///Clockwork Genesis,Expert,11
        ///Cryosleep,Expert,10
        ///Da Roots (Folk Mix),Expert,9
        ///Dawn,Expert,9
        ///D-Code,Expert,10
        ///Delirium,Expert,12
        ///Destiny,Expert,11
        ///Determinator,Expert,12
        ///Disconnected,Expert,9
        ///Disconnected Disco,Expert,9
        ///Disconnected -Hyper-,Expert,10
        ///Dis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string itg_expert {
            get {
                return ResourceManager.GetString("itg_expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anubis,Hard,8
        ///Bend Your Mind,Hard,9
        ///Boogie Down,Hard,8
        ///Bouff,Hard,9
        ///Bubble Dancer,Hard,7
        ///Changes,Hard,7
        ///Charlene,Hard,8
        ///Crazy,Hard,7
        ///Da Roots (Folk Mix),Hard,7
        ///Dawn,Hard,8
        ///Delirium,Hard,8
        ///Disconnected,Hard,8
        ///Disconnected -Hyper-,Hard,9
        ///Disconnected -Mobius-,Hard,8
        ///DJ Party,Hard,8
        ///Do U Love Me,Hard,6
        ///Don&apos;t Promise Me,Hard,6
        ///Don&apos;t Promise Me ~Happiness~,Hard,8
        ///Dreams of Passion,Hard,5
        ///Drifting Away,Hard,8
        ///Driving Force Classical,Hard,8
        ///Euphoria,Hard,9
        ///Fly Away,Hard,7
        ///Fly With Me,Hard,7        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string itg_hard {
            get {
                return ResourceManager.GetString("itg_hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !,Expert,12
        ///Agent Blatant,Expert,10
        ///Amore,Expert,9
        ///Anubis,Expert,10
        ///Baby Don&apos;t You Want Me,Expert,9
        ///Bend Your Mind,Expert,10
        ///Birdie,Expert,9
        ///Bloodrush,Expert,12
        ///Boogie Down,Expert,9
        ///Bouff,Expert,10
        ///Bumble Bee,Expert,9
        ///Charlene,Expert,11
        ///Clockwork Genesis,Expert,11
        ///Cryosleep,Expert,10
        ///Da Roots (Folk Mix),Expert,9
        ///Dawn,Expert,9
        ///D-Code,Expert,10
        ///Delirium,Expert,12
        ///Destiny,Expert,11
        ///Determinator,Expert,12
        ///Disconnected,Expert,9
        ///Disconnected Disco,Expert,9
        ///Disconnected -Hyper-,Expert,10
        ///Dis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string itg_hardexpert {
            get {
                return ResourceManager.GetString("itg_hardexpert", resourceCulture);
            }
        }
    }
}
